var resourcesDatabase = [
  {
    'State': 'NC',
    'Organization Name': 'Exceptional Children’s Assistance Center',
    'Website': 'http://www.ecac-parentcenter.org',
    'Address': 'ecac@ecacmail.org',
    'Phone Number': '704.892.1321 or toll free 1-800.962.6817',
    'Email': '',
    'Brief Description': 'ECAC is a private non-profit parent organization committed to improving the\nlives and education of ALL children through a special emphasis on children with disabilities. They provide information, education, outreach, and support to and for families with children across the state of North Carolina.',
    'Additional Information': '• Services:\no Assistance preparing for your child’s IEP:\n! Would you like assistance preparing for your child’s IEP Meeting or need someone to attend with you? If so, ECAC’s IEP Partners can help. If you would like more information about requesting an IEP Partner, call: 1-800- 962-6817 and ask to speak with a Parent Educator.\no ECAC Parent Training and Information Center: All services are provided to parents and families at no cost! (http://www.ecac-parentcenter.org/About-the- PTI.aspx?sid=17&pid=3&red=yes)\n! Toll Free Parent Info Line answered by Parents\n! Individual Assistance with educational issues\n! Parent and Professional Education workshops on a variety of topics ! Lending Library\n! Information packets, (paper and on CD)\n! NewsLine newsletter and ECAC Online!, our electronic newsletter\n! IEP Partners\n! Parent-to-Parent support\n! Assistance to parent groups\no Parent trainings and workshops:\n! Schedule a FREE workshop in your area: Please contact Margaret\nCampbell at 1-800-962-6817, ext. 317. o Hispanic Outreach Coordinator:\n! Teresa Peña, Parent Educator, Hispanic Outreach Coordinator, 1-800-962- 6817, ext. 324 tpena@ecacmail.org',
    'Notes': 'The following resources are from :https://www.cidd.unc.edu/docs/lend/ResourceGuideforParentsandFamiliesofChildrenwithSpecialHealthCareNeedsinNorthCarolina.pdf',
    'Tags': ''
  },
  {
    'State': 'NC',
    'Organization Name': 'Family Support Program',
    'Website': 'http://fsp.unc.edu',
    'Address': 'FSP.CDR@unc.edu',
    'Phone Number': '1-800.852.0042',
    'Email': 'FSP.CDR@unc.edu',
    'Brief Description': 'The mission of the Family Support Program is to promote\nprovide support for families with children who have special needs',
    'Additional Information': '• Services:\no All services are FREE and CONFIDENTIAL\no Information and Referral - to link families, caregivers, and providers to\ninformation about disabilities and diagnoses; parent-to-parent and other peer\nsupport; local, state, and national resources\no Find information about diagnosis and conditions',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'NC',
    'Organization Name': 'Family Support Network of North Carolina',
    'Website': 'http://www.fsnnc.org',
    'Address': '',
    'Phone Number': '1-800-852-0042',
    'Email': '',
    'Brief Description': 'Family Support" helps familes with a child who has special needs access services and supports. Family support is a community-based approach that: Increases the strength and resilience of families; Supports parents as they help their children with special needs achieve their full potential; Improves community providers’ capacity to serve families with children who have special needs',
    'Additional Information': "All FSN Regional Affiliates Offer:\nParent-to-Parent Support\nOne-to-one emotional and informational support for parents with a child who has special needs by a trained Support Parent. Matching parents of newly diagnosed children with experienced, trained support parents helps families adjust, adapt, and feel supported.\n \nSupport Parent Training\nA six-hour workshop for parents who have received support and gained experience that they now want to \"give back\" to parents who are new to the journey. This workshop equips experienced parents and caregivers with tools needed to provide new parents with social, emotional and informational support.\n \nInformation and Referral\nRegional FSN affiliates provide families and service providers with information and referrals to community and regional services and resources to help children and their families.\n \nSupport Groups and Workshops\nProvides social and emotional support, information and skills training, and leadership opportunities for families.\n \nService System Navigation Support\nAssistance navigating complex service systems to increase access to needed supports and services for children and their families.\n \nParent to Parent Matching for Rare Disorders\nAll FSN Affiliates are able to request Parent-to-Parent matches for rare diseases and disorders. FSNNC is an Alliance Member of Parent-to-Parent USA a national network of Parent to Parent programs across the country matching parents seeking support with experienced, trained 'Support Parents.",
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'NC',
    'Organization Name': 'The Arc of North Carolina',
    'Website': ': http://www.arcnc.org',
    'Address': '',
    'Phone Number': '800-662-8706 (toll free) or 919-782-4632 (local)',
    'Email': '',
    'Brief Description': '• Mission: The Arc of North Carolina has been providing advocacy and services to people\nwith intellectual and developmental disabilities since 1953. The Arc believes that all people with intellectual and developmental disabilities have strengths, abilities and inherent value, are equal before the law, and must be treated with dignity and respect.\n• Services:\no The Arc provides direct supports and services to people with intellectual and\ndevelopmental disabilities (I/DD) that enable people to lead full rich lives in the community.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'NC',
    'Organization Name': 'Carolina Institute for Developmental Disabilities',
    'Website': 'http://www.cidd.unc.edu',
    'Address': '',
    'Phone Number': '919-966-5171',
    'Email': 'info@cidd.unc.edu',
    'Brief Description': 'o The CIDD provides an array of clinical services for children and adults who have\nor are at risk for developmental disabilities.\no Clinical services: Assessment, consultation, and treatment options for individuals\nwith behavioral, learning, and developmental needs across the lifespan.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'NC',
    'Organization Name': 'TEACCH Autism Program:',
    'Website': 'http://teacch.com',
    'Address': '',
    'Phone Number': '919-966-2174',
    'Email': 'TEACCH@unc.edu',
    'Brief Description': 'Autism Program provides clinical services such as diagnostic evaluations, parent\ntraining and parent support groups, social play and recreation groups, individual counseling for higher-functioning clients, and supported employment',
    'Additional Information': '',
    'Notes': '',
    'Tags': 'Autism'
  },
  {
    'State': 'ME',
    'Organization Name': 'C.A.R.E.S., Inc.',
    'Website': 'https://caresinc.org',
    'Address': '134 Main St., Suite 2C\nWinthrop, ME 04364',
    'Phone Number': 'Phone: (207) 377-7055; Toll-Free Phone: 1-800-773-7055',
    'Email': 'kathy.despres@caresinc.org or\njenny.ardito@caresinc.org',
    'Brief Description': 'Advocacy, case management and assistive technology for Maine’s citizens with disabilities.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'ME',
    'Organization Name': 'Autism Society of Maine',
    'Website': 'https://www.asmonline.org/contact.aspx',
    'Address': '72B Main Street\nWinthrop, ME 04364',
    'Phone Number': '1-800-273-5200',
    'Email': 'info@asmonline.org',
    'Brief Description': 'ASM has Information Specialists who provide resource information to parents, guardians, and schools to support individuals with Autism Spectrum Disorders. The specialists will work one on one to assist families, guardians and Individuals on the Autism Spectrum as they navigate child or adult services. The ASM website also has lots of links and resource materials for families.',
    'Additional Information': '',
    'Notes': '',
    'Tags': 'Autism'
  },
  {
    'State': 'ME',
    'Organization Name': 'Disability Rights Center of Maine',
    'Website': 'https://drme.org',
    'Address': '160 Capitol Street, Suite 4 • Augusta, ME 04330',
    'Phone Number': '1-800-452-1948',
    'Email': 'https://drme.org/contact',
    'Brief Description': 'Providing the following services: Information and Referral; Individual Advocacy; Legal Representation; Education and Training; Assistance with Self-Advocacy.',
    'Additional Information': '',
    'Notes': '',
    'Tags': 'Legal'
  },
  {
    'State': 'ME',
    'Organization Name': 'Family Respite Program (through NAMI Maine)',
    'Website': 'https://www.namimaine.org/page/FamilyRespite',
    'Address': '52 Water Street, Hallowell, ME 04347',
    'Phone Number': '1-800-464-5767',
    'Email': 'info@namimaine.org',
    'Brief Description': 'NAMI Maine Family Respite exists to assist families by enabling a much needed break in the responsibility of caring for a child with significant developmental delays and behavioral or emotional disorders. Through a certified provider network, trained per diem staff are available to care for children with special needs in their communities so that their parents can get a break.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'ME',
    'Organization Name': 'Maine Down Syndrome Network',
    'Website': 'http://www.dsmaine.org',
    'Address': 'P. O. Box 705',
    'Phone Number': '(866) 571-2223',
    'Email': 'info@dsmaine.org',
    'Brief Description': 'Maine Down Syndrome Network (MDSN) is a network of families, professionals, and community members living in the state of Maine, who share the common goal of promoting awareness and acceptance of people with Down syndrome.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'ME',
    'Organization Name': 'Learning Disabilities Association of Maine',
    'Website': 'http://ldame.org',
    'Address': 'P O Box 314\nWestbrook, ME 04098',
    'Phone Number': '',
    'Email': 'info@ldame.org',
    'Brief Description': 'LDA serves children, families, and adults with learning disabilities through support, education, and advocacy.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'ME',
    'Organization Name': 'Maine Fragile X Resource Group',
    'Website': 'no website - this might be legit or not',
    'Address': '',
    'Phone Number': '657-2395',
    'Email': 'mainefragilex@yahoo.com',
    'Brief Description': 'Provides educational and emotional support for those affected by Fragile X, promotes public and professional awareness, and supports research toward improved treatments and a cure for Fragile X Syndrome.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'ME',
    'Organization Name': 'G.E.A.R. (Gaining Empowerment Allows Results) Parent Network',
    'Website': 'https://crisisandcounseling.org/services/gear/',
    'Address': '',
    'Phone Number': '626-3448 / 1-800-264-9224',
    'Email': '',
    'Brief Description': 'A program of crisis and counseling centers for parents of children with behavioral needs.  Through parent-to-parent sharing of experiences and knowledge, G.E.A.R. Parent Network empowers parents of children with behavioral health needs to build on their family’s strengths and to advocate for their family’s needs.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'ME',
    'Organization Name': 'Maine Developmental Disabilities Council',
    'Website': 'https://www.maineddc.org',
    'Address': '225 Western Avenue, Suite 4\nAugusta, ME 04330',
    'Phone Number': '207-287-4213 • 1-800-244-3990',
    'Email': 'Executive Director Nancy Cronin: nancy.e.cronin@maine.gov',
    'Brief Description': 'The Maine Developmental Disabilities Council (MDDC) is a partnership of people with disabilities, their families, and agencies which identifies barriers to community inclusion, self determination, and independence. The Council acts to effect positive change through advocacy, training, demonstration projects, and support for other inclusive and collaborative systemic change activities.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': '',
    'Organization Name': '',
    'Website': 'https://www.aane.org',
    'Address': '',
    'Phone Number': '',
    'Email': '',
    'Brief Description': '',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'MA',
    'Organization Name': 'Asperger / Autism Network (AANE)',
    'Website': 'https://www.aane.org',
    'Address': '51 Water Street, Suite 206, Watertown, MA 02472',
    'Phone Number': '(617) 393-3824',
    'Email': 'info@aane.org',
    'Brief Description': 'The Asperger / Autism Network (AANE) works with individuals, families, and professionals to help people with Asperger Syndrome and similar autism spectrum profiles build meaningful, connected lives',
    'Additional Information': '',
    'Notes': '',
    'Tags': 'Autism'
  },
  {
    'State': 'ME',
    'Organization Name': 'Maine Adaptive Sports & Recreation',
    'Website': 'https://www.maineadaptive.org',
    'Address': '8 Sundance Lane, Newry, Maine 04261',
    'Phone Number': '(207) 824-2440 / (800) 639-7770',
    'Email': 'info@maineadaptive.org',
    'Brief Description': 'Founded in 1982, Maine Adaptive is now the largest year-round adaptive recreation program in the state of Maine for adults and children with disabilities. Over 400 volunteers assist our athletes in appreciating the joys and challenges of sports participation.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'ME',
    'Organization Name': 'Family Resource Center for Disabilities and Special Needs',
    'Website': 'http://frcdsn.org',
    'Address': '1575 Savannah Highway, Ste. 6',
    'Phone Number': '843-266-1318',
    'Email': 'frc@frcdsn.org',
    'Brief Description': 'The FRC provides information services throughout the Lowcountry and was organized to promote opportunities for learning, inclusion, and empowerment for individuals with disabilities and special needs, their families, and their communities through such means as education, advocacy, and outreach.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'SC',
    'Organization Name': 'Family Connection',
    'Website': 'https://www.familyconnectionsc.org',
    'Address': '2712 Middleburg Drive\nSuite 103-B\nColumbia, SC 29204',
    'Phone Number': '803-252-0914',
    'Email': 'info@familyconnectionsc.org',
    'Brief Description': 'Families with shared experiences are uniquely qualified to help each other, offering support, guidance and encouragement. Because of this, all of our programs and services are family centered and based on the concept of parent-to-parent support. Whether you’re just beginning your journey or have a question along the way, we offer a variety of services and resources that can help.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'SC',
    'Organization Name': 'South Carolina Autism Society',
    'Website': 'https://scautism.org',
    'Address': '806 12th Street\nWest Columbia, SC 29169',
    'Phone Number': '803-750-6988',
    'Email': 'scas@scautism.org',
    'Brief Description': 'The mission of the South Carolina Autism Society (SCAS) is to equip those affected by Autism Spectrum Disorders with knowledge and support to maximize their quality of life.',
    'Additional Information': '',
    'Notes': '',
    'Tags': 'Autism'
  },
  {
    'State': 'SC',
    'Organization Name': 'Protection and Advocacy for People with Disabilities, Inc.',
    'Website': 'https://www.pandasc.org',
    'Address': '3710 Landmark Drive Suite 208\nColumbia, SC 29204',
    'Phone Number': '1-866-275-7273 (Voice)\n1-866-232-4525 (TTY)',
    'Email': 'info@pandasc.org',
    'Brief Description': 'Since 1977 P&A has been an independent, statewide, non-profit corporation that protects and advances the legal rights of people with disabilities.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'GA',
    'Organization Name': 'Parent to Parent of Georgia',
    'Website': 'http://p2pga.org',
    'Address': '3070 Presidential Parkway, Suite 130\nAtlanta, Georgia 30340',
    'Phone Number': '770-451-5484 / 800-229-2038',
    'Email': 'http://p2pga.org/index.php/contact-us-53/contact-p2p',
    'Brief Description': 'Families need to work together with service providers, agencies, and other professionals when making decisions that affect their children. Our education services provide opportunities for families to build on existing strengths to become stronger advocates.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'PA',
    'Organization Name': 'ABOARD’s Autism Connection of PA',
    'Website': 'https://autismofpa.org',
    'Address': '35 Wilson Street, Suite 100\nPittsburgh, PA 15223',
    'Phone Number': '1-800-827-9385',
    'Email': 'support@autismofpa.org',
    'Brief Description': 'Founded by parents in 1996, Autism Connection of Pennsylvania is a 501(c)(3) nonprofit, serving thousands of people seeking help for autism concerns. Professional staff, all parents who understand, provide telephone support, weekly autism news, autism-friendly activities, and coordinate more than 76 support groups across Pennsylvania.',
    'Additional Information': '',
    'Notes': '',
    'Tags': 'Autism'
  },
  {
    'State': 'PA',
    'Organization Name': 'Achieva (Chapter of The Arc)',
    'Website': 'www.achieva.info',
    'Address': 'Allegheny County\n711 Bingham Street\nPittsburgh PA 15203\nBeaver County\n105 Route 18\nBeaver Valley Mall\nMonaca PA 15061\nWestmoreland County\n316 Donohoe Road\nGreensburg PA 15601',
    'Phone Number': 'Allegheny County - 412.995.5000\n1.888.272.7229 (toll free); Beaver County - Monaca PA 15061\n724.775.1602; Westmoreland County - 724.837.8159',
    'Email': '',
    'Brief Description': '“ACHIEVA, formerly Arc Allegheny, is western Pennsylvania’s largest provider of comprehensive services and supports for children and adults with disabilities and their families.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'CT',
    'Organization Name': 'Autism Services and Resources Connecticut (ASRC)',
    'Website': 'www.autismconnecticut.org',
    'Address': '101 North Plains Industrial Road\nHarvest Park; Building 1A\nWallingford, CT 06492',
    'Phone Number': '203-265-7717',
    'Email': 'info@autismconnecticut.org',
    'Brief Description': 'ASRC is a support organization for individuals, families and professionals involved with autism spectrum disorders. They offer resources, support groups, workshops, conferences, on-site professional training and other services and supports.',
    'Additional Information': '',
    'Notes': '',
    'Tags': 'Autism'
  },
  {
    'State': 'CT',
    'Organization Name': 'Arc of Connecticut',
    'Website': 'www.thearcct.org',
    'Address': '43 Woodland Street, Suite 260 Hartford, CT 06105',
    'Phone Number': '860-246-6400',
    'Email': 'lsimoes@arcofct.org',
    'Brief Description': 'The Arc of Connecticut is an advocacy organization committed to protecting the rights of people with mental retardation and related developmental disabilities. They focus on promoting opportunitiesfor the person’s full inclusion within their communities. To findyour local Arc, please visit their website and click on the Arc/ Connecticut Chapters button on the left hand side.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'CT',
    'Organization Name': 'Americans with Disabilities Act Coalition of Connecticut (ADACC)',
    'Website': 'www.adacc.net',
    'Address': '60 B Weston Street\nHartford, CT 06120',
    'Phone Number': '860-800-2232',
    'Email': 'adacoalition@gmail.com',
    'Brief Description': 'The ADACC informs Connecticut citizens about the ADA and works to foster voluntary compliance. It offers a way for any interested person, business, employer and public agency to obtain information. They also provide training and technical assistance on rights and responsibilities under the ADA.',
    'Additional Information': '',
    'Notes': '',
    'Tags': 'Legal'
  },
  {
    'State': 'CT',
    'Organization Name': 'CCSN: The Center for Children with Special Needs and The Center for Indpendence',
    'Website': 'www.ccsnct.org',
    'Address': '2213 & 2300 Main Street\nGlastonbury, CT 06033',
    'Phone Number': '860-430-1762',
    'Email': 'info@ccsnct.org',
    'Brief Description': 'CCSN is an interdisciplinary clinic specializing in the diagnosis, evaluation and treatment of children and adolescents with complex neurodevelopmental disabilities, particularly autism spectrum disorders, pediatric chronic illness, developmental disabilities and severe behavioral difficulties.',
    'Additional Information': '',
    'Notes': '',
    'Tags': 'Autism'
  },
  {
    'State': 'CT',
    'Organization Name': 'The Center of Excellence on Autism Spectrum Disorders',
    'Website': 'www.southernct.edu/asdcenter',
    'Address': 'Southern CT State University\nDavis Hall\n501 Crescent Street\nNew Haven, CT 06515',
    'Phone Number': '203-392-5929; 203-392-5925',
    'Email': 'erenr1@southernct.edu',
    'Brief Description': 'The Center of Excellence on Autism Spectrum Disorders serves as a resource and collaborative partner by developing, validating and delivering effective, innovative training, services and technical assistance to teachers, other school-based personnel, families and community services providers in the use of evidence-based practices for individuals ages 3-21 with autism spectrum disorders in Connecticut.',
    'Additional Information': '',
    'Notes': '',
    'Tags': 'Autism'
  },
  {
    'State': 'CT',
    'Organization Name': 'Children’s Law Center of Connecticut, Inc.',
    'Website': 'www.clcct.org',
    'Address': '30 Arbor Street, North\nHartford, CT 06106',
    'Phone Number': '860-232-9993; 888-LAW-DOOR',
    'Email': 'clc@clcct.org',
    'Brief Description': 'Children’s Law Center of Connecticut, Inc, is a private nonprofit organization that represents disadvantaged children in family court.',
    'Additional Information': '',
    'Notes': '',
    'Tags': 'Legal'
  },
  {
    'State': 'CT',
    'Organization Name': 'Connecticut Families for Effective Autism Treatment, Inc. (CT FEAT)',
    'Website': 'www.ctfeat.org',
    'Address': 'P.O. Box 370352\nWest Hartford, CT 06137-0352',
    'Phone Number': '860-571-3888',
    'Email': 'ctfeat1@ctfeat.org',
    'Brief Description': 'CT FEAT provides information and resources to help parents evaluate the effectiveness of current autism treatment. They approach and support families implementing intensive treatment programs based on the principles of Applied Behavior Analysis (ABA).',
    'Additional Information': '',
    'Notes': '',
    'Tags': 'Autism'
  },
  {
    'State': 'CT',
    'Organization Name': 'Connecticut Family Support Network',
    'Website': 'www.ctfsn.org',
    'Address': '1074 Main Street.\nSouth Glastonbury, CT 06073',
    'Phone Number': '860-430-5679',
    'Email': 'timperati@ctfsn.org',
    'Brief Description': 'The Connecticut Family Support Network is a statewide network of parents of children with a wide range of disabilities and special health care needs who provide information, resources and training to families',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'CT',
    'Organization Name': 'African Caribbean American Parents of Children with Disabilities, Inc. (AFCAMP)',
    'Website': 'https://www.afcamp.org/',
    'Address': '49 Woodland Street Hartford, CT 06105',
    'Phone Number': '860-548-9959',
    'Email': 'info@afcamp.org',
    'Brief Description': 'Trains parents of children with disabilities from every school district in Hartford to become advocates within their schools, and assists them with training other parents to become advocates. Offers education, training, and resource materials on disability awareness, disability laws including ADA, and rights and responsibilities of parents of children with disabilities.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'CT',
    'Organization Name': 'Connecticut Parent Advocacy Center: Special Education Advocacy/Disability Rights',
    'Website': 'www.cpacinc.org',
    'Address': '338 Main Street, Niantic, CT 06357',
    'Phone Number': '860-739-3089',
    'Email': 'cpac@cpacinc.org',
    'Brief Description': "Offers information and resource materials for parents of children with special educational needs and assistance with advocating for their children's education, employment, and independent living needs.",
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'CT',
    'Organization Name': "FAVOR - Family Advocacy Organization for Children's Behavioral Health: Special Education Advocacy/System Advocacy * Mental Health Issues",
    'Website': 'www.favor-ct.org',
    'Address': '185 Silas Deane Highway\nWethersfield, CT 06109-1219',
    'Phone Number': '(860) 563-3232',
    'Email': 'jhawke@favor-ct.org',
    'Brief Description': "FAVOR provides advocacy, family leadership training, and support for parents, families, and professional caregivers on behavioral health issues, and legislative advocacy and training on children's behavioral health and special education issues.  FAVOR accepts all referrals and provides services based on current capacity.",
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'CT',
    'Organization Name': 'Diability Rights Connecticut, Inc.',
    'Website': 'https://www.disrightsct.org',
    'Address': '846 Wethersfield Avenue\nHartford, Connecticut 06114',
    'Phone Number': '800-842-7303;  860-990-5199',
    'Email': 'info@disrightsct.org',
    'Brief Description': 'Education Advocates provide information, advocacy, and support for parents of children in the special education system. Families in need of advocacy can contact a Special Education Advocate.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'CT',
    'Organization Name': 'Ari Of Connecticut: School to Adult Life Transition Services',
    'Website': 'https://arict.org/',
    'Address': '174 Richmond Hill Avenue, Stamford, CT 06902',
    'Phone Number': '203-324-9258',
    'Email': 'Staff emails are listed here: https://arict.org/ContactPeople.html',
    'Brief Description': "ARI's staff will participate in IEP and transition planning meetings, and will assist each student ages 15+ to develop their transition goals in order to work toward the future.",
    'Additional Information': '',
    'Notes': '',
    'Tags': 'Transition'
  },
  {
    'State': 'CT',
    'Organization Name': 'SpedConnecticut: Special Education Advocacy',
    'Website': 'http://www.spedconnecticut.com/spedindex.shtml',
    'Address': '75 Charter Oak Avenue\nSuite 105\nHartford, CT 06106-1903',
    'Phone Number': '860-560-1711',
    'Email': 'Info@spedconnecticut.org',
    'Brief Description': 'SpEdConnecticut, Inc. formerly known as the Learning Disabilities Association of Connecticut , is a nonprofit organization dedicated to making a positive difference in the educational experience of children with disabilities.  We provide information, training, and advocacy support to families as they seek appropriate educational services for their children with special education needs.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'CT',
    'Organization Name': 'SPEDNET New Canaan',
    'Website': 'http://www.spednet.org',
    'Address': 'P.O.Box 1612. New Canaan, CT 06840',
    'Phone Number': '',
    'Email': 'info@spednet.org',
    'Brief Description': 'SPED*NET Special Education Network of New Canaan, Ltd. (SPED*NET New Canaan”) is organized exclusively to educate the public on special education and disability-related issues.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'CT',
    'Organization Name': 'SPEDNET Wilton',
    'Website': 'www.spednetwilton.org',
    'Address': '44 Harbor View Avenue\nNorwalk , CT 06854',
    'Phone Number': '',
    'Email': 'info@spednetwilton.org',
    'Brief Description': 'Special education information and advocacy group for parents and staff of students with special needs offers seminars during the school year; lends books and videos of its speakers, provides handouts and information, and publishes an online special education handbook.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'CT',
    'Organization Name': 'Western Connecticut Association for Human Rights: Planning and Placement Team',
    'Website': 'www.wecahr.org',
    'Address': '57 North Street Suite 223 B\nDanbury , CT 06810',
    'Phone Number': '203-792-3540',
    'Email': 'advocate@wecahr.org',
    'Brief Description': 'Includes reviewing (in person or by telephone) school issues that concern the parent and the child, preparation for the Planning and Placement Team (PPT) meetings, attendance and participation in the PPT session, follow-up with the parent as needed to ensure that conclusions agreed upon at the meeting(s) are enacted.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'CT',
    'Organization Name': 'Padres Abriendo Puertas, Inc.',
    'Website': 'http://padresabriendopuerta.wixsite.com/pap-website',
    'Address': '151 New Park Avenue, Suite 115\nHartford , CT 06106',
    'Phone Number': '860-365-2411',
    'Email': 'PadresAbriendoPuertasINC@aol.com',
    'Brief Description': 'Statewide special education advocacy group for Hispanic parents teaches parents to be advocates for their children with disabilities and offers workshops, resource materials, monthly information exchanging meetings and parent-to-parent support.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'CT',
    'Organization Name': 'Greater Hartford Legal Aid, Inc.',
    'Website': 'www.ghla.org',
    'Address': '999 Asylum Avenue, 3rd Floor\nHartford , CT 06105',
    'Phone Number': '800-453-3320; 860-541-5000; 860-541-5003',
    'Email': 'ghla@ghla.org',
    'Brief Description': 'Advocacy, legal representation, advice, and information for some education related issues, including children and youth in need of special education services, residency issues, suspension and expulsions, and education rights of children who are homeless.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'CT',
    'Organization Name': 'UConn University Center for Excellence in Developmental Disabilities',
    'Website': 'https://uconnucedd.org/',
    'Address': 'The Exchange Building #4\n270 Farmington Avenue, Suite 181\nFarmington, CT 06030',
    'Phone Number': '860.679.1500',
    'Email': 'infoucedd@uchc.edu',
    'Brief Description': "Parent Leadership and Advocacy is a program consisting of six modules covering a range of relevant topics and issues. These modules will help parents learn how to advocate for their child's needs as well as to improve the quality of life for other children and families in Connecticut.",
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'CT',
    'Organization Name': 'Smart Kids with Learning DIsabilities',
    'Website': 'www.smartkidswithld.org',
    'Address': '38 Kings Highway North\nWestport , CT 06880',
    'Phone Number': '203-226-6831',
    'Email': 'info@smartkidswithld.org',
    'Brief Description': 'Learning disabilities education organization provides information and support to parents of children with learning disabilities or attention deficit hyperactivity disorder (ADHD) primarily through its website, blog, regional educational programs or through its e-newsletter.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'NJ',
    'Organization Name': 'Statewide Parent Advocacy Network (SPAN)',
    'Website': 'http://www.spanadvocacy.org/content/programs',
    'Address': '35 Halsey St., Fourth Floor, Newark, New Jersey        07102',
    'Phone Number': '973-642-8100; : 1-800-654-SPAN',
    'Email': '',
    'Brief Description': 'The SPAN Parent Advocacy Network is an independent 501(c)3 organization committed to empowering families as advocates and partners in improving education, health, and mental health outcomes for infants, toddlers, children and youth. SPAN is a “first stop” for New Jersey families.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'NJ',
    'Organization Name': 'Advancing Opportunities',
    'Website': 'https://advopps.org',
    'Address': '1005 Whitehead Road Extension, Suite 1 Ewing, New Jersey 08638',
    'Phone Number': '609-882-4182/Toll-Free: 1-888-322-1918',
    'Email': 'info@advopps.org',
    'Brief Description': 'Advancing Opportunities, Inc., is a 501 (c) 3 non-profit organization providing services and supports to people with disabilities and their families so they can live independently.  Recognized as one of the leading disability service providers in the state of New Jersey, the agency is committed to person-centered services delivered in the community.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'NJ',
    'Organization Name': 'Alliance of Private Special Education Schools of North Jersey',
    'Website': 'https://specialeducationalliancenj.org',
    'Address': '170 Changebridge Rd. C5-3\nMontville, NJ 07045',
    'Phone Number': '973-407-0596',
    'Email': '',
    'Brief Description': 'An alliance of more than 30 state-approved private special education schools in Northern and Central New Jersey whose members are committed to great outcomes.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'NJ',
    'Organization Name': 'The Arc of New Jersey',
    'Website': 'https://www.arcnj.org',
    'Address': '985 Livingston Avenue\nNorth Brunswick, NJ 08902',
    'Phone Number': '732.246.2525',
    'Email': 'info@arcnj.org',
    'Brief Description': "The Arc of New Jersey is the state's largest organization advocating for and serving children and adults with intellectual and developmental disabilities and their families. The Arc of New Jersey is an affiliated chapter of The Arc, and community-based services are available statewide through our strong network of Local County Chapters.",
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'NJ',
    'Organization Name': 'Autism Family Services of NJ',
    'Website': 'https://autismfamilyservicesnj.org',
    'Address': '1 AAA Drive, Suite 203\nTrenton, NJ 08691',
    'Phone Number': '(800) 376-2345',
    'Email': '',
    'Brief Description': 'Autism Family Services of New Jersey is a state-wide, non-profit charitable agency dedicated to helping improve the quality of life for people affected by autism and their loved ones. Autism Family Services of New Jersey is a statewide organization with offices located in Brick, Parsippany, Trenton and Barrington.',
    'Additional Information': '',
    'Notes': '',
    'Tags': 'Autism'
  },
  {
    'State': 'NJ',
    'Organization Name': 'Autism Family Services of NJ - Shore Area Office',
    'Website': 'https://autismfamilyservicesnj.org',
    'Address': 'Lions Head Office Park\n35 Beaverson Blvd.\nBuilding 11\nBrick, NJ 08723',
    'Phone Number': '(732) 262-8020',
    'Email': '',
    'Brief Description': '',
    'Additional Information': '',
    'Notes': '',
    'Tags': 'Autism'
  },
  {
    'State': 'NJ',
    'Organization Name': 'Autism Family Services of NJ - Northern Regional Office',
    'Website': 'https://autismfamilyservicesnj.org',
    'Address': '322 US Highway 46 Suite 290\nParsippany, NJ 07054',
    'Phone Number': '(973) 244-0850',
    'Email': '',
    'Brief Description': '',
    'Additional Information': '',
    'Notes': '',
    'Tags': 'Autism'
  },
  {
    'State': 'NJ',
    'Organization Name': 'Autism Family Services of NJ - Southern Regional Office',
    'Website': 'https://autismfamilyservicesnj.org',
    'Address': '208 White Horse Pike, Suite 8\nBarrington, NJ 08007',
    'Phone Number': '(856) 858-5900',
    'Email': '',
    'Brief Description': '',
    'Additional Information': '',
    'Notes': '',
    'Tags': 'Autism'
  },
  {
    'State': 'NJ',
    'Organization Name': 'The Family Support Center of NJ',
    'Website': 'http://www.fscnj.org',
    'Address': '1 AAA Drive, Suite 203\nTrenton, NJ 08691',
    'Phone Number': '800) 372-6510',
    'Email': '',
    'Brief Description': 'The Family Support Center is a clearinghouse of up-to-date information on a national, state and local family support programs, services and disabilities. The Center offers a “One-Stop-Shopping” approach to individuals seeking information on disabilities and services by providing them with easy access to a comprehensive array of services',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'NJ',
    'Organization Name': 'Epilepsy Services of New Jersey',
    'Website': 'https://epilepsyservicesnj.org',
    'Address': '1 AAA Drive, Suite 203\nTrenton, NJ 08691',
    'Phone Number': '(800) 376-2345',
    'Email': '',
    'Brief Description': 'Epilepsy Services of New Jersey, an affiliate of The Family Resource Network, is a state-wide, non-profit charitable agency dedicated to helping to improve the quality of life for people affected by epilepsy and their loved ones.',
    'Additional Information': '',
    'Notes': '',
    'Tags': 'Epilepsy'
  },
  {
    'State': 'NJ',
    'Organization Name': 'Caregivers of New Jersey',
    'Website': 'https://njcaregivers.org',
    'Address': '1 AAA Drive, Suite 203\nTrenton, NJ 08691',
    'Phone Number': '877-265-6360',
    'Email': '',
    'Brief Description': 'Facilitating unique and individualized planning processes in helping people with disabilities make informed choices. Our person-centered teams support life destination decisions and help you find the right paths to achieve them.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'NJ',
    'Organization Name': 'The Family Resource Network',
    'Website': 'https://www.familyresourcenetwork.org/resources/',
    'Address': '1 AAA Drive, Suite 203\nTrenton, NJ 08691',
    'Phone Number': '(800) 336-5843',
    'Email': '',
    'Brief Description': 'The Family Resource Network (FRN) is dedicated to offering individuals and their families with continuing needs the greatest opportunities, resources and services to support a full and happy life.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'NJ',
    'Organization Name': 'Autism New Jersey',
    'Website': 'https://www.autismnj.org',
    'Address': '500 Horizon Drive, Suite 530 \nRobbinsville, NJ 08691',
    'Phone Number': '609.588.8200',
    'Email': 'information@autismnj.org',
    'Brief Description': 'Connects those with autism to necessary resources to achieve their full potential',
    'Additional Information': '',
    'Notes': '',
    'Tags': 'Autism'
  },
  {
    'State': 'NJ',
    'Organization Name': 'New Jersey Association of the Deaf, Inc.',
    'Website': 'https://www.deafnjad.org',
    'Address': '253-8 Echelon Road\nVoorhees, NJ 09043',
    'Phone Number': '609-242-0240',
    'Email': 'njadeaf@gmail.com',
    'Brief Description': 'This Association shall be the focal point of all cooperating agencies within the State in promoting the welfare of the deaf in educational measures, in employment, in legislation, and in any other field pertaining to or affecting the deaf in New Jersey in their pursuit of economic security, equal opportunity, and all their just rights and privileges as citizens.',
    'Additional Information': '',
    'Notes': '',
    'Tags': 'Deafness'
  },
  {
    'State': 'NJ',
    'Organization Name': 'National Federation of the Blind-New Jersey',
    'Website': 'https://www.nfbnj.org',
    'Address': '254 Spruce Street\nBloomfield, NJ 07003',
    'Phone Number': '866-632-1940',
    'Email': 'nfbnj1@verizon.net',
    'Brief Description': 'Every day we raise the expectations of blind people, because low expectations create obstacles between blind people and our dreams.',
    'Additional Information': '',
    'Notes': '',
    'Tags': 'Blindness'
  },
  {
    'State': 'NJ',
    'Organization Name': 'Association for Special Children and Families',
    'Website': '',
    'Address': '',
    'Phone Number': '',
    'Email': '',
    'Brief Description': '',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'NJ',
    'Organization Name': 'Education Law Center',
    'Website': 'http://www.edlawcenter.org',
    'Address': '60 Park Place, Suite 300\nNewark, NJ 07102',
    'Phone Number': '973-624-1815',
    'Email': 'elc@edlawcenter.org',
    'Brief Description': 'Founded in 1973, the Education Law Center (ELC) serves as the leading voice for New Jersey’s public school children and has become one of the most effective advocates for equal educational opportunity and education justice in the United States. Widely recognized for groundbreaking court rulings on behalf of at-risk students, ELC also promotes educational equity through coalition building, litigation support, policy development, communications, and action-focused research in New Jersey, in other states, and at the federal level.',
    'Additional Information': '',
    'Notes': '',
    'Tags': 'Legal'
  },
  {
    'State': 'NJ',
    'Organization Name': 'Alliance for the Betterment of Citizens with Disabilities',
    'Website': 'http://www.abcdnj.org',
    'Address': '127 Route 206, Suite 18 Hamilton, NJ 08610',
    'Phone Number': '609-581-8375',
    'Email': 'Admin@abcdnj.org',
    'Brief Description': 'The Alliance for the Betterment of Citizens with Disabilities (ABCD) is a New Jersey-based non-partisan not for profit organization dedicated to improving the lives of people with complex physical and neurological developmental disabilities so that they may have the opportunity to attain the highest level of purpose and dignity.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'NJ',
    'Organization Name': 'New Jersey Coalition for Inclusive Education',
    'Website': 'https://www.njcie.org',
    'Address': '9 Auer Court, Suite H\nEast Brunswick, NJ 08810',
    'Phone Number': '732-613-0400',
    'Email': 'team@njcie.org',
    'Brief Description': 'NJCIE supports inclusive education for all students with disabilities as a fundamental civil right. NJCIE views inclusion as a means to creating an equitable, socially-just democratic society.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'NJ',
    'Organization Name': 'Disability Rights New Jersey',
    'Website': 'https://www.drnj.org',
    'Address': '210 South Broad Street, 3rd Fl. Trenton, NJ 08608',
    'Phone Number': '800-922-7233',
    'Email': 'advocate@drnj.org',
    'Brief Description': 'Private, non-profit, consumer-directed organization established to advocate for, advise and assist individuals and families with disabilities.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'NJ',
    'Organization Name': 'Rutgers School of Law Special Education Clinic',
    'Website': 'https://law.rutgers.edu/legal-clinics',
    'Address': '123 Washington Street Newark, New Jersey 07102',
    'Phone Number': '973-353-5576',
    'Email': '',
    'Brief Description': 'Clinic law students provide representation and advocacy to parents and caregivers seeking to obtain appropriate early intervention and educational services and placements, and educate parents and others involved in the lives of children with disabilities about their legal rights and responsibilities.',
    'Additional Information': '',
    'Notes': '',
    'Tags': 'Legal'
  },
  {
    'State': 'NJ',
    'Organization Name': 'The Boggs Center on Developmental Disabilities',
    'Website': 'http://rwjms.rutgers.edu/boggscenter/',
    'Address': 'Rutgers, The State University of New Jersey\nLiberty Plaza, 335 George Street\nNew Brunswick, NJ 08901',
    'Phone Number': '(732) 235-9300',
    'Email': 'http://rwjms.rutgers.edu/boggscenter/contact_us/reqform.php',
    'Brief Description': 'The Boggs Center is New Jersey’s federally designated University Center for Excellence in Developmental Disabilities Education, Research, and Service. Part of Rutgers Robert Wood Johnson Medical School, The Boggs Center prepares students through interdisciplinary programs, provides community training and technical assistance, conducts research, and disseminates information and educational materials.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'NJ',
    'Organization Name': 'Special Education Advocate NJ',
    'Website': 'https://www.specialedadvocatenj.com',
    'Address': '',
    'Phone Number': '973-980-2190',
    'Email': 'doug@specialedadvocatenj.com',
    'Brief Description': 'If your child has an IEP, but it doesn’t seem to be effective, or you think that your child may need special education services, you need to work closely with the school’s child study team.  I provide fee-for-service non-attorney advocacy services for parents and their children.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'FL',
    'Organization Name': 'Disability Rights Florida',
    'Website': 'http://www.disabilityrightsflorida.org/about/about_us',
    'Address': '2473 Care Drive, Suite 200 \nTallahassee, Florida 32308',
    'Phone Number': '1-800-342-0823',
    'Email': '',
    'Brief Description': 'Disability Rights Florida was founded in 1977 as the statewide designated protection and advocacy system for individuals with disabilities in the State of Florida. Disability Rights Florida is a not-for-profit corporation that has authority and responsibility under nine federal grants. Our services are free and confidential.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'FL',
    'Organization Name': 'The ARC of Florida, Inc',
    'Website': 'www.arcflorida.org',
    'Address': '2898 Mahan Drive, Suite 1\nTallahassee, Florida 32308',
    'Phone Number': '(800) 226-1155',
    'Email': '',
    'Brief Description': 'The Arc of Florida works with local, state and national partners and advocates for people with intellectual disabilities, autism, spina bifida, cerebral palsy (CP), prader-willi syndrome and other developmental disabilities to be fully included in all aspects of their community.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'FL',
    'Organization Name': 'Bright Expectations',
    'Website': 'http://www.floridahealth.gov/programs-and-services/people-with-disabilities/bright-expectations/index.html',
    'Address': 'Florida Department of Health \n4052 Bald Cypress Way, Bin A13 \nTallahassee, FL 32399-1721',
    'Phone Number': '(850) 245-4465',
    'Email': 'BE@flhealth.gov',
    'Brief Description': 'provides resources and information on developmental disabilities for pregnant women, health care providers, parents and families',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'FL',
    'Organization Name': 'Easter Seals Florida',
    'Website': 'info@dsacf.org',
    'Address': '520 N. Semoran Blvd. Suite 280, Orlando, Florida 32807',
    'Phone Number': '(407) 306-9766',
    'Email': '',
    'Brief Description': "Offers a variety of services to help people with disabilities address life's challenges and achieve personal goals.",
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'FL',
    'Organization Name': 'The Family Café, Inc',
    'Website': 'https://www.familycafe.net',
    'Address': '820 E Park Ave. Suite F-100, Tallahassee, Florida 32301',
    'Phone Number': '(888) 309-CAFÉ (2233)',
    'Email': 'info@familycafe.net',
    'Brief Description': 'Brings together individuals with disabilities and their families with state agencies, non-profit organizations and other service providers for networking opportunities',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'FL',
    'Organization Name': 'Florida Association for Infant Mental Health',
    'Website': 'https://www.faimh.org',
    'Address': 'PO Box 6423\nBrandon, FL 33508',
    'Phone Number': '850-296-7002',
    'Email': 'info@faimh.org',
    'Brief Description': 'Focused on prevention, identification and treatment of emotional and behavioral disorders in children birth to age 5',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'FL',
    'Organization Name': 'Florida Developmental Disabilities Council, Inc.',
    'Website': 'www.fddc.org',
    'Address': '124 Marriott Drive, Suite 203, Tallahassee, Florida 32301',
    'Phone Number': '(800) 580-7801',
    'Email': 'fddc@fddc.org',
    'Brief Description': 'Advocates and promotes meaningful participation in all aspects of life for Floridians with developmental disabilities',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'FL',
    'Organization Name': 'Florida Diagnostic & Learning Resources System (FDLRS)',
    'Website': 'http://www.fdlrs.org',
    'Address': '3841 Reid Street | Palatka, FL 32177',
    'Phone Number': '(386) 312-2265',
    'Email': 'ahearnm@nefec.org',
    'Brief Description': 'Florida Diagnostic & Learning Resources System (FDLRS)',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'FL',
    'Organization Name': 'Florida School for the Deaf and the Blind (FSDB)',
    'Website': 'http://www.fsdb.k12.fl.us/',
    'Address': '207 N. San Marco Avenue - St. Augustine, FL 32084',
    'Phone Number': '(800) 344-3732',
    'Email': '',
    'Brief Description': 'A fully accredited state public school and outreach center available tuition-free to eligible Pre-K and K-12 deaf/hard of hearing or blind/visually impaired students, including meals, boarding, transportation and other services.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'FL',
    'Organization Name': 'Center for Autism and Related Disabilities (CARD)',
    'Website': 'http://florida-card.org/index.htm',
    'Address': 'multiple sites - http://florida-card.org/map.htm',
    'Phone Number': '850-245-0476',
    'Email': 'Diana.McLendon@fldoe.org',
    'Brief Description': 'The Center for Autism & Related Disabilities (CARD) provides support and assistance with the goal of optimizing the potential of people with autism spectrum disorder and related disabilities.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'FL',
    'Organization Name': 'Autism Society of Florida (ASF)',
    'Website': 'https://autismfl.com',
    'Address': 'Autism Society of Florida, P.O. Box 677055, Orlando, Florida 32867',
    'Phone Number': '407.207.3388',
    'Email': '',
    'Brief Description': 'Autism Society of Florida statewide affiliates are your best source of information and support. Affiliates are volunteer-led by parents, care providers and other professionals reaching out to individuals with Autism Spectrum Disorder and their families with information, support, and encouragement.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'FL',
    'Organization Name': 'Family Network on Disabilities of Florida, Inc.',
    'Website': 'https://fndusa.org',
    'Address': '2196 Main Street, Suite L, Dunedin, FL 34698',
    'Phone Number': '(727) 523-1130',
    'Email': 'richlabelle @ fndusa.org',
    'Brief Description': 'FND is a grassroots organization for persons with disabilities and their families that is family-centered and family-driven.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'FL',
    'Organization Name': 'Florida Alliance for Assistive Services and Technology, Inc',
    'Website': 'https://faast.org',
    'Address': '820 E Park Ave, D-200\nTallahassee, FL 32301',
    'Phone Number': '(850) 487-3278',
    'Email': 'info@faastinc.org',
    'Brief Description': 'The Florida Alliance for Assistive Services and Technology is the State of Florida’s number one resource for assistive technology (AT).',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'FL',
    'Organization Name': 'Florida Commission for the Transportation Disadvantaged',
    'Website': 'https://ctd.fdot.gov/index.htm',
    'Address': 'Office Location 2740 Centerview Drive, Suite 1A\nTallahassee, Florida 32301; Mailing Address: 605 Suwannee Street, MS-49\nTallahassee, Florida 32399-0450',
    'Phone Number': '1 (800) 983-2435    OR    (850) 410-5700',
    'Email': 'CTDOmbudsman@dot.state.fl.us',
    'Brief Description': 'The Florida Commission for the Transportation Disadvantaged (CTD) is an independent agency responsible for the coordination of transportation services for older adults, persons with disabilities, persons of low income and children at risk.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'FL',
    'Organization Name': 'Agency for Persons with Disabilities (APD)',
    'Website': 'http://apd.myflorida.com/about/',
    'Address': 'Agency for Persons with Disabilities\n4030 Esplanade Way, Suite 380\nTallahassee, FL 32399-0950',
    'Phone Number': '(850) 488-4257',
    'Email': 'APD.Info@apdcares.org',
    'Brief Description': 'The APD works in partnership with local communities and private providers to assist people who have developmental disabilities and their families. APD also provides assistance in identifying the needs of people with developmental disabilities for supports and services.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'FL',
    'Organization Name': 'Bright Feats',
    'Website': 'http://www.brightfeats.com',
    'Address': '',
    'Phone Number': '1.407.620.9355',
    'Email': 'Rori@BrightFeats.com',
    'Brief Description': 'Free community resource directory for parents/caregivers with children that have medical, educational and special needs',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'FL',
    'Organization Name': 'Down Syndrome Association of Central Florida',
    'Website': 'https://www.dsacf.org',
    'Address': '204 N Wymore Rd Winter Park, FL 32789',
    'Phone Number': '407.478.5621',
    'Email': 'info@dsacf.org',
    'Brief Description': 'DSACF is the leading voice for all individuals with Down syndrome and their families. We offer hope, acceptance and empowerment through advocacy, education and awareness as we guide individuals with Down syndrome through life. Together, we create a Central Florida community composed of and dedicated to individuals with Down syndrome – and those who love them – so that each may realize their potential.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'FL',
    'Organization Name': 'Family Care Council of Florida',
    'Website': 'http://www.fccflorida.org/area-7-family-care-council.html',
    'Address': 'Marks Street Senior Recreation Center \nThe Cypress Room\n99 East Marks Street\nOrlando, FL 32803',
    'Phone Number': '(407) 254-1066',
    'Email': '',
    'Brief Description': 'Advocates, educates and empowers individuals with developmental disabilities and their families.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'NV',
    'Organization Name': 'Angel Flight West',
    'Website': 'http://www.angelflightwest.org',
    'Address': '3161 Donald Douglas Loop South\nSanta Monica, CA 90405',
    'Phone Number': '(310) 390-2958',
    'Email': 'info@angelflightwest.org',
    'Brief Description': "(AFW) arranges free air transportation for people who need to travel long distances to access needed care. Generous volunteer pilots donate their time, their flying skills, and all costs. There's never a charge for an Angel Flight West mission.  AFW also serves as the “official airline” for specialty camps attended by children from Nevada.",
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': '',
    'Organization Name': 'Autism Coalition of Nevada',
    'Website': 'http://www.aconv.org',
    'Address': '',
    'Phone Number': '850.291.6778',
    'Email': 'acon@aconv.org',
    'Brief Description': 'The Autism Coalition of Nevada (ACON) is comprised of representatives from various autism advocacy organizations, agencies and professionals who serve Nevadans with Autism Spectrum Disorder and related Neurodevelopmental Disorders throughout our state.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': '',
    'Organization Name': 'Autism Treatment Assistance Program (ATAP)',
    'Website': 'http://adsd.nv.gov/Programs/Autism/ATAP/ATAP/',
    'Address': '3416 Goni Road, Suite D-132\nCarson City, NV 89706',
    'Phone Number': '(775) 687-4210',
    'Email': 'adsdatap@adsd.nv.gov',
    'Brief Description': 'Nevada’s Autism Treatment Assistance Program (ATAP) was created to assist parents and caregivers with the expensive cost of providing Autism-specific treatments to their child with Autism Spectrum Disorder (ASD). ATAP is a statewide program that provides temporary assistance and funding to pay for evidenced-based treatment such as Applied Behavior Analysis (ABA) for children on the Autism Spectrum, who are under the age of 20 and are diagnosed as a person with Autism Spectrum Disorder by a physician, psychologist, child/adolescent psychiatrist, pediatric neurologist or other qualified professional. A diagnosis from a multidisciplinary team is acceptable when in accompanied by an appropriate assessment report.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': '',
    'Organization Name': 'Family TIES of Nevada',
    'Website': 'https://familytiesnv.net',
    'Address': '',
    'Phone Number': 'Health Information Line: (866) 326-8437; (775) 823-9500',
    'Email': '',
    'Brief Description': 'Family TIES of Nevada is a statewide nonprofit organization that serves people with disabilities throughout their lifespan, and supports their families and professionals who work on their behalf.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': '',
    'Organization Name': 'Deaf Centers of Nevada',
    'Website': 'http://dhharc.org',
    'Address': '',
    'Phone Number': '',
    'Email': '',
    'Brief Description': 'Deaf Centers of Nevada provides education, advocacy, support and resources to families, children and individuals who have hearing impairments.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': '',
    'Organization Name': 'Family Resource Centers of Nevada',
    'Website': 'http://dhhs.nv.gov/Programs/Grants/Programs/FRC/Family_Resource_Center/',
    'Address': 'Muliple: http://dhhs.nv.gov/uploadedFiles/dhhsnvgov/content/Programs/Grants/Programs/FRC/FRC_Statewide_DirectoryREV.pdf',
    'Phone Number': '(702) 920-6515',
    'Email': '',
    'Brief Description': 'Family Resource Centers provide case management, information, and referrals for individuals and families in need of assistance in accessing services and programs that will strengthen and support the family. FRCs collaborate with other agencies, schools, faith-based organizations, and government agencies to assist families to obtain needed services. FRCs emphasize community based, collaborative services that are culturally competent, accessible, and flexible.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': '',
    'Organization Name': 'The Lovaas Center',
    'Website': 'http://thelovaascenter.com',
    'Address': '5550 W. Flamingo Rd. Suite C-5\nLas Vegas, Nevada 89103',
    'Phone Number': '(702) 877-2520',
    'Email': '',
    'Brief Description': 'The Lovaas Center provides early intensive behavioral intervention, which incorporates Applied Behavior Analysis (ABA) and was developed in the psychology department of UCLA under the direction of Dr. O. Ivar Lovaas. It is intended to provide intensive early intervention for young children (under four years old when treatment starts) with autism.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': '',
    'Organization Name': 'Nevada 2-1-1',
    'Website': 'https://www.nevada211.org',
    'Address': '',
    'Phone Number': '2-1-2001',
    'Email': '',
    'Brief Description': 'On-line access/referral to basic human services, health resources, employment support services, support for seniors and persons with disabilities, and programs for children, youth, and families in Nevada. And 2-1-1 is an easy-to-remember telephone number you can dial that connects callers to free information about critical health and human services available in their community.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': '',
    'Organization Name': 'Nevada Act Early',
    'Website': 'http://www.nevadaactearly.org',
    'Address': '',
    'Phone Number': 'Questions: 775-682-7019',
    'Email': 'dvigil@medicine.nevada.edu',
    'Brief Description': 'Nevada Act Early, mainly an online resourceeducates and brings awareness to parents, healthcare professionals and educators in all communities across Nevada about early warning signs of neurodevelopmental disorders. Learn about early warning signs of Autism and find services for your child.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': '',
    'Organization Name': 'Nevada Disability Advocacy and Law Center: Statewide Overview',
    'Website': 'http://www.ndalc.org',
    'Address': '',
    'Phone Number': '',
    'Email': '',
    'Brief Description': 'The Nevada Disability Advocacy & Law Center (NDALC) is a private, statewide non-profit organization that serves as Nevada’s federally-mandated protection and advocacy system for human, legal, and service rights for individuals with disabilities.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': '',
    'Organization Name': 'Nevada Disability Advocacy and Law Center: Las Vegas',
    'Website': 'http://www.ndalc.org',
    'Address': '2820 West Charleston Boulevard #11\nLas Vegas, NV 89102',
    'Phone Number': '702-257-8150',
    'Email': 'lasvegas@ndalc.org',
    'Brief Description': '',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': '',
    'Organization Name': 'Nevada Disability Advocacy and Law Center: Reno',
    'Website': 'http://www.ndalc.org',
    'Address': '1875 Plumas Street #1\nReno, NV 89509',
    'Phone Number': '775-333-7878',
    'Email': 'reno@ndalc.org',
    'Brief Description': '',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': '',
    'Organization Name': 'Nevada Disability Advocacy and Law Center: Elko',
    'Website': 'http://www.ndalc.org',
    'Address': '905 Railroad Street #104B\nElko, NV 89801',
    'Phone Number': '775-777-1590',
    'Email': 'elko@ndalc.org',
    'Brief Description': '',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': '',
    'Organization Name': 'Nevada Care Connection',
    'Website': 'https://nevadaadrc.com/about-us/adrc-contact-us',
    'Address': '3416 Goni Road | Suite D-132 | Carson City, NV 89706',
    'Phone Number': 'Techinal Assistance: Southern Nevada: 702-486-3600 | Rural & Northern Nevada: 775-687-0585',
    'Email': 'adsdhelpdesk@adsd.nv.gov',
    'Brief Description': 'The purpose of this website is to provide up-to-date resources and information that will support and assist caregivers as they care for family members and friends that are frail or disabled.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': '',
    'Organization Name': 'NV Center for Excellence in Developmental Disabilities',
    'Website': 'https://www.unr.edu/nced',
    'Address': '1664 N. Virginia Street\n\nReno, NV 89557',
    'Phone Number': '(775) 784-4921',
    'Email': 'nced@unr.edu',
    'Brief Description': 'Works with consumers, agencies, and programs to assist Nevadans with developmental disabilities of all ages to be independent and productive citizens who are included in their communities.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': '',
    'Organization Name': "Nevada Children's Mental Health- Division of Child and Family Services (DCFS)",
    'Website': 'http://dcfs.nv.gov/Programs/CMH/',
    'Address': '',
    'Phone Number': '',
    'Email': '',
    'Brief Description': 'DCFS provides mental health treatment services to children between birth and six years of age with emotional disturbance or high risk factors for emotional and behavioral disturbance and associated developmental delays. Provides community-based outpatient, individual and family oriented mental health services for children from six through seventeen years of age.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': '',
    'Organization Name': 'Nevada Dual Sensory Impairment Project',
    'Website': 'http://www.unr.edu/educ/ndsip/',
    'Address': 'Nevada Dual Sensory Impairment Project\nCollege of Education\nUniversity of Nevada, Reno/MS 299\nReno, NV 89557',
    'Phone Number': '775-784-6471 (phone)\n1-877-621-5042 (toll free in Nevada)',
    'Email': 'MAD@unr.edu',
    'Brief Description': 'The purpose is to enhance educational services and provide technical assistance to support parents, services providers, and other service agencies in meeting the educational needs of children and youth, birth through 21 years, who have dual sensory impairments-diagnosed with both vision and hearing impairments.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': '',
    'Organization Name': "Nevada Governor's Council on Developmental Disabilities",
    'Website': 'http://www.nevadaddcouncil.org',
    'Address': '896 W. Nye Lane Suite 202 \nCarson City, NV 89703',
    'Phone Number': '775-684-8619',
    'Email': 'elmarquez@dhhs.nv.gov',
    'Brief Description': 'Their mission is to provide resources at the community level which promote equal opportunity and life choices for people with disabilities through which they may positively contribute to Nevada society.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': '',
    'Organization Name': 'Nevada P.E.P',
    'Website': 'http://www.nvpep.org',
    'Address': '7211 W. Charleston Blvd.\nLas Vegas, Nevada 89117',
    'Phone Number': '(702) 388-8899',
    'Email': 'pepinfo@nvpep.org',
    'Brief Description': "Parents Encouraging Parents - Nevada's Parent Training & Information Center for families of children with disabilities. Our Mission - To increase the opportunities for home, community and school success for children with disabilities, including those who are at risk or who have serious emotional disturbances, their families and their service providers, through education, encouragement and empowerment activities.",
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'OR',
    'Organization Name': 'FACTOegon',
    'Website': 'https://factoregon.org/',
    'Address': '2475 SE Ladd Ave. Suite 430\nPortland, OR 97214',
    'Phone Number': '(503) 786-6082 or 1 (888)-988-3228',
    'Email': 'support@factoregon.org',
    'Brief Description': 'By families, for families. FACT is your one-stop resource! We are able to support you with: Understanding special education\nTrainings, workshops, and in-services; Family activities and get-togethers; Person-centered planning tools; Information and resources;  A support line  to answer your questions and talk to a parent whose been there.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'OR',
    'Organization Name': 'Oregon Council on Developmental Disabilities (OCDD)',
    'Website': 'https://ocdd.org/',
    'Address': '2475 SE Ladd Avenue, Suite 231, Portland, OR 97214.',
    'Phone Number': '(503) 235-0369',
    'Email': 'info@ocdd.org',
    'Brief Description': 'The Oregon Council on Developmental Disabilities is made up of self-advocates, family members, representatives of advocacy organizations, and community organizations that provide services and supports to people with developmental disabilities.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'OR',
    'Organization Name': 'Easterseals Oregon',
    'Website': 'http://www.easterseals.com/',
    'Address': '7300 SW Hunziker St, Portland, OR 97223',
    'Phone Number': '503-228-5108',
    'Email': '',
    'Brief Description': 'Children and adults with disabilities and special needs find highest-quality services designed to meet their individual needs when they come to Easterseals. Teams of therapists, teachers and other health professionals help each person overcome obstacles to independence and reach his or her personal goals. Easterseals also includes families as active members of any therapy program, and offers the support families need.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': 'OR',
    'Organization Name': 'Disability Rights Oregon',
    'Website': 'https://droregon.org',
    'Address': 'Disability Rights Oregon\n511 SW 10th Avenue, Suite 200\nPortland, Oregon 97205',
    'Phone Number': '503-243-2081 or 1-800-452-1694',
    'Email': '',
    'Brief Description': 'We assist with legal problems directly related to disabilities.  We do this in a variety of ways, which include:\nProviding information, tools and referrals that empower self-advocacy; Promoting awareness of civil rights; Investigating and addressing reports of abuse and/or neglect; Pursuing policy changes and legislation that benefit people with disabilities; Representing individuals in cases where legal expertise is needed; Litigation when necessary',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': '',
    'Organization Name': 'Special Olympics Oregon',
    'Website': 'www.soor.org',
    'Address': '419 NE 10th Ave., Portland, OR 97232',
    'Phone Number': '503-248-0600',
    'Email': 'info@soor.org',
    'Brief Description': 'Special Olympics Oregon represents the largest disability population in Oregon, providing life-changing opportunities to children, youth and adults living with intellectual disabilities through our year-round programs and services. Learn more about what we do and who we serve.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': '',
    'Organization Name': 'Autism Society of Oregon',
    'Website': 'http://autismsocietyoregon.org/',
    'Address': '5100 SW MacAdam Ave, Suite 400, Portland, OR 97239',
    'Phone Number': '1-888-Autism-1 (1-888-288-4761)',
    'Email': 'info@AutismSocietyOregon.org]]',
    'Brief Description': 'The state chapter of the Autism Society of America (ASA,) which is the oldest and largest grassroots organization within the autism community. Autism Society of Oregon (ASO) seeks to empower individuals with autism, their families, and their service providers to improve the quality of their lives through support and information.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': '',
    'Organization Name': 'University Center for Excellence in Developmental Disabilities',
    'Website': 'https://www.ohsu.edu/xd/research/centers-institutes/institute-on-development-and-disability/ucedd/',
    'Address': '3181 S.W. Sam Jackson Park Rd.\nPortland, Oregon 97239-3098',
    'Phone Number': '503-494-8364',
    'Email': 'ucedd@ohsu.edu',
    'Brief Description': 'University Centers for Excellence in Developmental Disabilities (UCEDD) are organizations, located at universities across the nation, that focus on improving the lives of people with disabilities and their families. Through education, service, research and outreach activities, we work to be instrumental in changing policy, providing training, and educating the public about major disability issues.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': '',
    'Organization Name': 'Disability Compass',
    'Website': 'http://www.disabilitycompass.org/',
    'Address': '',
    'Phone Number': '',
    'Email': '',
    'Brief Description': 'Disability Compass is an interactive web-based resource center, developed in Oregon, providing local community and national information on services, products, and special health care resources for people with disabilities, their families, and their supporters. Please visit this site to further search for links to resources within Oregon communities, statewide, and abroad.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  },
  {
    'State': '',
    'Organization Name': 'The Arc of Oregon',
    'Website': 'https://thearcoregon.org',
    'Address': '2405 Front St #120\nSalem, OR 97301',
    'Phone Number': '(503) 581-2726',
    'Email': '',
    'Brief Description': 'A statewide membership organization of more than 2000 individuals, working together to create a better tomorrow for individuals with intellectual and developmental disabilities, and their families. The Arc of Oregon advocates for the rights and full community participation of all children and adults with intellectual and developmental disabilities.',
    'Additional Information': '',
    'Notes': '',
    'Tags': ''
  }
]
